import os
import sys
import asyncio
import edge_tts

# Fix for Pillow 10+ compatibility with MoviePy
import PIL.Image
if not hasattr(PIL.Image, 'ANTIALIAS'):
    PIL.Image.ANTIALIAS = PIL.Image.LANCZOS

from moviepy.editor import *

if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')

# 1. The Script generated by our AI Agent
VIDEO_SCRIPT = """
5 Times Cristiano Ronaldo shocked the world!
Number 1. The impossible bicycle kick against Juventus.
Number 2. The gravity-defying header against Sampdoria.
Number 3. The iconic knuckleball free kick against Portsmouth.
Number 4. The legendary World Cup hat-trick against Spain.
Number 5. Winning five Ballon d'Ors to cement his legacy.
Who is your GOAT? Comment down below and subscribe!
"""

# Voice settings (en-US-ChristopherNeural is a good dramatic male voice)
VOICE = "en-US-ChristopherNeural" 
AUDIO_FILE = "voiceover.mp3"
OUTPUT_VIDEO = "final_shorts.mp4"

async def generate_audio(text, output_file):
    print(f"[*] Generating AI Voiceover using voice: {VOICE}...")
    communicate = edge_tts.Communicate(text, VOICE)
    await communicate.save(output_file)
    print(f"[+] Voiceover saved successfully as {output_file}\n")

def create_video():
    print("[*] Assembling the Video with real CR7 footage...")
    
    # Load the generated audio
    try:
        audio_clip = AudioFileClip(AUDIO_FILE)
        duration = audio_clip.duration
    except Exception as e:
        print(f"[!] Error loading audio: {e}")
        return

    print(f"[*] Audio duration is {duration:.2f} seconds.")
    
    # Load the real CR7 video
    try:
        video_file = "cr7_source.mp4"
        if not os.path.exists("cr7_source.f401.mp4") and not os.path.exists(video_file):
            print("[*] Background video missing. Downloading for Cloud...")
            os.system('python -m yt_dlp -f "bestvideo[ext=mp4]/best[ext=mp4]" -o "cr7_source.mp4" "ytsearch1:cristiano ronaldo 4k edit"')
        elif os.path.exists("cr7_source.f401.mp4"):
            video_file = "cr7_source.f401.mp4"

        video_clip = VideoFileClip(video_file)
        # Resize to 1080x1920 (Shorts resolution), cropping if necessary
        # We loop the video so it matches the length of the audio
        from moviepy.video.fx.all import loop, crop
        
        # Simple center crop for vertical
        (w, h) = video_clip.size
        target_w = h * 9 / 16
        x_center = w / 2
        
        bg_clip = crop(video_clip, width=target_w, height=h, x_center=x_center)
        bg_clip = bg_clip.resize(height=1920, width=1080)
        
        bg_clip = loop(bg_clip, duration=duration)
    except Exception as e:
        print(f"[!] Error loading video clip: {e}")
        print("Falling back to ColorClip...")
        bg_clip = ColorClip(size=(1080, 1920), color=(20, 20, 20)).set_duration(duration)
    
    # Composite video
    video = CompositeVideoClip([bg_clip])
    video = video.set_audio(audio_clip)

    # Write the result to a file
    print(f"[*] Rendering final video to {OUTPUT_VIDEO} (this might take a few seconds)...")
    video.write_videofile(
        OUTPUT_VIDEO, 
        fps=24, 
        codec="libx264", 
        audio_codec="aac",
        logger=None # Disable long logs in terminal
    )
    print(f"\n🎉 Video successfully rendered: {os.path.abspath(OUTPUT_VIDEO)}")
    print("=====================================================")
    print("Next Step: Replace the 'ColorClip' in code with an actual folder of CR7 video clips!")

if __name__ == "__main__":
    print("=====================================================")
    print("🎬 AI AGENT: STARTING VIDEO PRODUCTION PIPELINE")
    print("=====================================================\n")
    
    # 1. Generate Voiceover
    asyncio.run(generate_audio(VIDEO_SCRIPT, AUDIO_FILE))
    
    # 2. Assemble and Render Video
    create_video()
